
export const CarsBrands = {
  CAR : [
    "Acura",
    "Alfa Romeo",
    "AMC",
    "Aston Martin",
    "Audi",
    "Avanti",
    "Bentley",
    "BMW",
    "Buick",
    "Cadillac",
    "Chevrolet",
    "Chrysler",
    "Daewoo",
    "Daihatsu",
    "Datsun",
    "DeLorean",
    "Dodge",
    "Eagle",
    "Ferrari",
    "FIAT",
    "Fisker",
    "Ford",
    "Freightliner",
    "Geo",
    "GMC",
    "Honda",
    "HUMMER",
    "Hyundai",
    "Infiniti",
    "Isuzu",
    "Jaguar",
    "Jeep",
    "Kia",
    "Lamborghini",
    "Lancia",
    "Land Rover",
    "Lexus",
    "Lincoln",
    "Lotus",
    "Maserati",
    "Maybach",
    "Mazda",
    "McLaren",
    "Mercedes-Benz",
    "Mercury",
    "Merkur",
    "MINI",
    "Mitsubishi",
    "Nissan",
    "Oldsmobile",
    "Peugeot",
    "Plymouth",
    "Pontiac",
    "Porsche",
    "RAM",
    "Renault",
    "Rolls-Royce",
    "Saab",
    "Saturn",
    "Scion",
    "smart",
    "SRT",
    "Sterling",
    "Subaru",
    "Suzuki",
    "Tesla",
    "Toyota",
    "Triumph",
    "Volkswagen",
    "Volvo",
    "Yugo"
  ],
  MOTORHOME : [
    "ABI",
    "Adria",
    "Ahorn",
    "Airstream",
    "Alpha",
    "Arca",
    "Atlas",
    "Autoroller",
    "Autostar",
    "Avento",
    "BK Bleubird",
    "Bavaria-Camp",
    "Bawemo",
    "Beisl",
    "Bela",
    "Benimar",
    "Beyerland",
    "Bimobil",
    "Burow",
    "CI International",
    "CS Reisemobile",
    "Ca-Mo-Car",
    "Carado",
    "Caravelair",
    "Caretta",
    "Carnaby Caravans",
    "Caro",
    "Carthago",
    "Challenger",
    "Chateau",
    "Chausson",
    "Chrysler",
    "Citroen",
    "Clever",
    "Coachmen",
    "Concorde",
    "Cristall",
    "Damon",
    "Dehler",
    "Delta",
    "Dopfer",
    "Dreamer",
    "Due Erre",
    "Eifelland",
    "Elnagh",
    "Esterel",
    "Etrusco",
    "Euramobil",
    "Euro Liner",
    "Fendt",
    "Ffb/Tabbert",
    "Fiat",
    "Fleetwood",
    "Fleurette",
    "Florium",
    "Ford",
    "Ford/Reimo",
    "Forster",
    "Frankia",
    "General Motors",
    "Gigant",
    "Giottiline",
    "Globe-Traveller",
    "Globecar",
    "Glücksmobil",
    "Granduca",
    "HRZ",
    "HYMERCAR",
    "Hehn",
    "Heku",
    "Holiday Rambler",
    "Home-Car",
    "ICF",
    "Illusion",
    "Itineo",
    "Iveco",
    "Joint",
    "Kabe",
    "Karmann",
    "Kentucky",
    "Kip",
    "La Strada",
    "Lacet",
    "Laika",
    "Linne-Liner",
    "Lmc",
    "M+M Mobile",
    "MAN",
    "Ma-Bu",
    "Maesss",
    "Malibu",
    "Mazda",
    "Mclouis",
    "Mercedes-Benz",
    "Miller",
    "Mirage",
    "Mitsubishi",
    "Mobilvetta",
    "Monaco",
    "Moncayo",
    "Morelo",
    "Neo-Traveller",
    "Neotec",
    "Niesmann+Bischoff",
    "Niewiadow",
    "NobelART",
    "Nordstar",
    "Opel",
    "Orangecamp",
    "Ormocar",
    "PLA",
    "Pemberton",
    "Peugeot",
    "Phoenix",
    "Pilote",
    "Procab",
    "Pössl",
    "RMB",
    "Raclet",
    "Rapido",
    "Reimo",
    "Reisemobile Beier",
    "Renault",
    "Reydam",
    "Rimor",
    "Riva",
    "Riviera",
    "Roadcar",
    "Roadtrek",
    "Robel-Mobil",
    "Robeta",
    "Rockwood",
    "Roller Team",
    "SEA",
    "Schwabenmobil",
    "Selbstbau",
    "Sonstige/Other",
    "Sprite",
    "Stephex motorhomes",
    "Sterckeman",
    "Sun Living",
    "Sunlight",
    "Sunroller",
    "Swift",
    "T@b",
    "Tabbert",
    "Tec",
    "Tischer",
    "Trigano",
    "Triple E",
    "Ultra",
    "VANTourer",
    "VW",
    "Vario",
    "Victory",
    "Volkner",
    "Weinsberg",
    "Weippert",
    "Westfalia",
    "Wilk",
    "Willerby",
    "Wingamm",
    "Winnebago",
    "Woelcke",
    "Other"
  ],
  MOTOCYCLES : [
    "AJP",
    "Adiva",
    "Aeon",
    "Aprilia",
    "Aspess Power",
    "Axy",
    "Azel",
    "BMW",
    "Bajaj",
    "Benelli",
    "Beta",
    "Bimota",
    "Borile",
    "Boss Hoss",
    "Buell",
    "Bultaco",
    "CCM",
    "CF Moto",
    "CH Racing",
    "CMC",
    "CPI",
    "CR&S",
    "Cagiva",
    "Dado Motors",
    "Daelim",
    "Derbi",
    "Ducati",
    "E-Tropolis",
    "E-max",
    "Ecomission",
    "Fantic Motor",
    "Garelli",
    "Gas Gas",
    "Generic",
    "Ghezzi-Brian",
    "GiMotori",
    "GiPuma",
    "Gilera",
    "Green Mobility Italia",
    "HDM",
    "HM",
    "HP Power",
    "Harley-Davidson",
    "Headbanger",
    "Honda",
    "Honda Dall'Ara",
    "Hupper",
    "Husaberg",
    "Husqvarna",
    "Hyosung",
    "Indian",
    "Italjet",
    "Jawa",
    "KRC",
    "KTM",
    "Kawasaki",
    "Kawasaki KL",
    "Keeway",
    "Kreidler",
    "Kymco",
    "LML",
    "Lambretta",
    "Laverda",
    "Leonart",
    "Lingben",
    "Linhai",
    "MBK",
    "MV Agusta",
    "MZ",
    "Magni",
    "Maico",
    "Malaguti",
    "Mash",
    "Millepercento",
    "Mondial",
    "Montesa",
    "Moto Bellini",
    "Moto Guzzi",
    "Moto Morini",
    "Moto Rumi",
    "MotoBi",
    "Motom",
    "Motor Union",
    "Nipponia",
    "Norton",
    "Nox",
    "Ossa",
    "Over",
    "PGO",
    "Paton",
    "Peda Motor",
    "Peugeot",
    "Piaggio",
    "Polini",
    "Quadro",
    "Quantya",
    "RedMoto Honda",
    "Renault",
    "Rieju",
    "Royal Enfield",
    "SWM",
    "Sachs",
    "Scorpa",
    "Sherco",
    "Siamoto",
    "Steed",
    "Suzuki",
    "Suzuki Valenti",
    "Sym",
    "TGB",
    "TM Racing",
    "Terra Modena",
    "Triumph",
    "Ural",
    "Vectrix",
    "Vertemati",
    "Victory",
    "Vor",
    "WT Motors",
    "Yamaha"
  ],
    AGRICULTURA: [
        "AG-CHEM",
        "AGT",
        "Accord",
        "Aebi",
        "Agco",
        "Agco Massey Ferguson",
        "Agria",
        "Agrimaster",
        "Agritec",
        "Agromec",
        "Agrotop",
        "Ahlmann",
        "Airman",
        "Al-Ko",
        "Alasco",
        "Alf",
        "Alfa-Laval",
        "Alö",
        "Amazone",
        "Annaburger",
        "As-Motor",
        "Atlas",
        "Augl",
        "Ausa",
        "Autowrap",
        "Auwärter",
        "BBG",
        "BGU",
        "Baas",
        "Bab Bamps",
        "Badema",
        "Baecht",
        "Barigelli",
        "Baselier Agri Tech",
        "Bauer",
        "Bautz",
        "Becker",
        "Beinlich",
        "Belarus",
        "Benken",
        "Beral",
        "Bergmann",
        "Bergmeister",
        "Berthoud",
        "Berti",
        "Binderberger",
        "Biso",
        "Bleinroth",
        "Bobcat",
        "Bomag",
        "Bomfort",
        "Botsch",
        "Bovlund",
        "Brantner",
        "Braud",
        "Braun",
        "Bremer",
        "Brenderup",
        "Bressel",
        "Breviglieri",
        "Briggs&Stratton",
        "Brill",
        "Briri",
        "Brix",
        "Bruns",
        "Bucher",
        "Bugnot",
        "Burgstaller",
        "Busatis",
        "Bvl-Van Lengerich",
        "Böckmann",
        "Bögballe",
        "Bühler",
        "Caeb",
        "Caffini",
        "CanAgro",
        "Capello",
        "Cargotec",
        "Carraro",
        "Case-Ih",
        "Chemo",
        "Claas",
        "Clark",
        "Continental",
        "Cramer",
        "Crown",
        "Cub Cadet",
        "Dalbo",
        "Dameco",
        "Dammann",
        "David Brown",
        "Degenhart",
        "Dela",
        "Delaval",
        "Deutz-Fahr",
        "Dexheimer",
        "Diadem",
        "Diamond",
        "Diedam",
        "Dierling",
        "Doll",
        "Dolmar",
        "Doosan",
        "Doppstadt",
        "Doublet Record",
        "Douven",
        "Dubex",
        "Dutzi",
        "Dynapac",
        "Dücker",
        "Düvelsdorf",
        "EVG",
        "Eberhardt",
        "Eckhard",
        "EcoLog",
        "Eder",
        "Efco",
        "Egholm",
        "Eicher",
        "Einsiedler",
        "Eisele",
        "Epsilon",
        "Ering",
        "Eschlböck",
        "Esm",
        "Esta",
        "Eurogarden",
        "Euromatch",
        "Eurotrac",
        "Eurotrans",
        "Evers",
        "Expom",
        "FMG",
        "Fahr",
        "Fahrzeugwerk Orthaus",
        "Faresin",
        "Farm",
        "Farmall",
        "Farmtech",
        "Fasterhold",
        "Faun",
        "Fehrenbach",
        "Felber",
        "Fella",
        "Fendt",
        "Ferris",
        "Fiatagri",
        "Fiona",
        "Fischer",
        "Fleming",
        "Fliegl",
        "Flötzinger",
        "Ford",
        "Ford New Holland",
        "Fortschritt",
        "Fortuna",
        "Foton/Eurotrac",
        "Frandent",
        "Fricke",
        "Frimokar",
        "Fristein",
        "Frost",
        "Fähse",
        "Gallagher",
        "Gallignani",
        "Galucho",
        "Gaspardo",
        "Gassner",
        "Gebo",
        "Gehl",
        "Gerblinger",
        "Geringhoff",
        "Gilbers",
        "Gilibert",
        "Gkn-Walterscheid",
        "Gloria",
        "Gmelin",
        "Goldhofer",
        "Goldoni",
        "Good Year",
        "Gotha",
        "Grammer",
        "Grasdorf",
        "Grasshopper",
        "Grau",
        "GreenMech",
        "Greenland",
        "Gremo",
        "Griesser",
        "Grimme",
        "Gruber",
        "Gruse",
        "Gutbrod",
        "Göweil",
        "Güldner",
        "Güstrow",
        "Güttler",
        "H&S",
        "Hagedorn",
        "Hako",
        "Hamm",
        "Hanomag",
        "Hardi",
        "Hassia",
        "Hatzenbichler",
        "He-Va",
        "Hella",
        "Hesston",
        "Heywang",
        "Hieble",
        "Himel",
        "Hitachi",
        "Hoegen-Dijkhof",
        "Hoffmann",
        "Holar",
        "Holder",
        "Holmer",
        "Holzknecht",
        "Honda",
        "Horsch",
        "Howard",
        "Hsm",
        "Husqvarna",
        "Hydrema",
        "Hypro",
        "Hüdig",
        "Hürlimann",
        "IHC",
        "IKF Kehrmaschine",
        "Igland",
        "Indeco",
        "Ingersoll-Rand",
        "Intergarden",
        "Inuma",
        "Irrifrance",
        "Isaria",
        "Iseki",
        "Isera",
        "Isuzu",
        "Iveco",
        "JCB",
        "JLG",
        "Jabelmann",
        "Jakoby",
        "Jeantil",
        "Jessernigg",
        "Jet",
        "Jf",
        "Joba",
        "John Deere",
        "Jost",
        "Junghenrich",
        "K-Trac",
        "Kaelble",
        "Kawasaki",
        "Kawec",
        "Keenan",
        "Kemper",
        "Kerner",
        "Kersten",
        "Kinze",
        "Kioti",
        "Kirovetz",
        "Kleber",
        "Kleine",
        "Knies",
        "Knoche",
        "Knorr",
        "Kobelco",
        "Kock",
        "Kockums",
        "Kotschenreuther",
        "Kotte",
        "Kraft",
        "Kramer",
        "Krampe",
        "Kretzer",
        "Krieger",
        "Krone",
        "Kröger",
        "Kubota",
        "Kuhn",
        "Kuxmann",
        "Kverneland",
        "Kyllingstad",
        "Kynast",
        "Kärcher",
        "Kässbohrer",
        "Köckerling",
        "Kögel",
        "Köla",
        "Köppl",
        "L.T.S.",
        "LS-Traktor",
        "Lamborghini",
        "Land Pride",
        "Landini",
        "Landsberg",
        "Langendorf",
        "Lanz",
        "Lasco",
        "Laverda",
        "Leffers",
        "Lely",
        "Lemken",
        "Lescha",
        "Leyland",
        "Lh-Agro",
        "Liebherr",
        "Lifter",
        "Lifton",
        "Linde",
        "Lindner",
        "Lochmann",
        "Logset",
        "Lohmann",
        "Lombardini",
        "Lucas",
        "MAN",
        "Maihöfer",
        "Mailleux",
        "Manitou",
        "Mann & Hummel",
        "Mannesmann Rexroth",
        "Marmix",
        "Marxen",
        "Mascar",
        "Maschio",
        "Matbro",
        "Mayer",
        "Mb-Trac",
        "Mc Hale",
        "McConnell",
        "Mccormick",
        "Meels",
        "Meiller",
        "Mengele",
        "Mercedes-Benz",
        "Merlo",
        "Michelin",
        "Miedema",
        "Mitsubishi",
        "Monosem",
        "Moreau",
        "Morra",
        "Mountfield",
        "Mtd",
        "Muh",
        "Mulag",
        "Multicar",
        "Murray",
        "Musmax",
        "Mörtl",
        "Müller",
        "Müthing",
        "Naud",
        "Netagco",
        "Neuero",
        "Neuson",
        "New Holland",
        "New Idea",
        "Niemeyer",
        "Nissan",
        "Nodet",
        "Noe",
        "Nordsten",
        "O&K",
        "Omarv",
        "Oregon",
        "Ortolan",
        "Pagliari",
        "Pasquali",
        "Patu",
        "Paus",
        "Peecon",
        "Pegoraro",
        "Pellenc",
        "Perkins",
        "Perrot",
        "Pfanzelt",
        "Pfau",
        "Pichon",
        "Pirelli",
        "Platz",
        "Pleintinger",
        "Plötz",
        "Polaris",
        "Ponsse",
        "Porsche",
        "Posch",
        "Pose",
        "Pronar",
        "Pz-Vicon",
        "Pöttinger",
        "Quivogne",
        "RTS",
        "Rabe",
        "Rain Bird",
        "Ralle",
        "Ransomes",
        "Rapid",
        "Rau",
        "Rauch",
        "Razol",
        "Rebo",
        "Redekop",
        "Reekie",
        "Reermann",
        "Reform",
        "Reformwerke Wels",
        "Regent",
        "Renault",
        "Resant Aebi",
        "Reuter",
        "Ricona",
        "Rieve",
        "Ritter",
        "Rmh",
        "Roe",
        "Roell",
        "Rolland",
        "Ropa",
        "Roth",
        "Rotina",
        "Rotoland",
        "Rottne",
        "Rumpstad",
        "SIP",
        "Saabel",
        "Sabo",
        "Sambron",
        "Same",
        "Sampo",
        "Sandtec",
        "Saphir",
        "Sauer",
        "Sauerburger",
        "Sauter",
        "Saxonia",
        "Scan Agro",
        "Scania",
        "Schaeff",
        "Schanzlin",
        "Scheifele",
        "Schliesing",
        "Schlüter",
        "Schmotzer",
        "Schrattenegger",
        "Schriever",
        "Schuitemaker Sr Hollan",
        "Schwarzmüller",
        "Schäffer",
        "Seko",
        "Sesam",
        "Sgariboldi",
        "Shelbourne",
        "Shibaura",
        "Sieger",
        "Sileo",
        "Siloking",
        "Silowolff",
        "Silvatec",
        "Simba",
        "Simex",
        "Simon",
        "Simulta",
        "Sitrex",
        "Sky Trak",
        "Solo",
        "SpraCoupe",
        "Stapel",
        "Stegstedt",
        "Steyr",
        "Stiga",
        "Stihl",
        "Still",
        "Stockey & Schmitz",
        "Stoll",
        "Strautmann",
        "Streumaster",
        "Streumix",
        "Stricker",
        "Strobel",
        "Structural",
        "Struik",
        "Sulky",
        "Taarup",
        "Takeuchi",
        "Tanco",
        "Taurus",
        "Tebbe",
        "Tecnoma",
        "Tecumseh",
        "Thaler",
        "Tielbürger",
        "Tietjen",
        "Tigges",
        "Tim",
        "Timberjack",
        "Timken",
        "Tohr",
        "Toku",
        "Tolsma",
        "Tornado",
        "Toro",
        "Trioliet",
        "Truma",
        "Trumag",
        "Tuchel",
        "Tume",
        "Tym",
        "Tünnissen & Stocks",
        "UTC",
        "Uni Hofschlepper",
        "Unia",
        "Unifarm",
        "Unimog",
        "Unsinn Fz-Technik",
        "Ursus",
        "Vag",
        "Valmet",
        "Valtra",
        "Ventzki",
        "Vermeer",
        "Vicon",
        "Viking",
        "Vogel&Noot",
        "Vogelsang",
        "Volvo",
        "Von Der Heide",
        "Von Heyking",
        "Väderstadt",
        "WAP",
        "Wabco",
        "Wacker",
        "Waeco",
        "Walker",
        "Waltershausen",
        "Webasto",
        "Weber",
        "Weidemann",
        "Weiste",
        "Welger",
        "Werdau",
        "Werner",
        "Westeria",
        "Westfalia",
        "Westwood",
        "Weweler",
        "White",
        "Wibro",
        "Widder",
        "Wiedemann",
        "Wiegard",
        "Willemsen",
        "Wilms",
        "Wima",
        "Wolagri",
        "Wolf",
        "Woods",
        "Wühlmaus",
        "Yale",
        "Yardpro",
        "ZF",
        "Zaslaw",
        "Zeppelin",
        "Zetor",
        "Zettelmeyer",
        "Zuidberg",
        "Zunhammer",
        "Zürn",
        "Överum"
      ],
      
      
      //@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
      //@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
      //@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
      
      
      
      
      
      BUS: [
        "Berkhof",
        "Bova",
        "Citroen",
        "Contrac",
        "DAF",
        "Den Oudsten",
        "Drögmöller",
        "Eos - Coach",
        "Ernst Auwärter",
        "Evobus",
        "Fiat",
        "Ford",
        "Gangloff",
        "ICF",
        "Ikarus",
        "Irisbus",
        "Irizar",
        "Isuzu",
        "Iveco",
        "Iveco Bus",
        "Jonckheere",
        "Kowex",
        "Kröger",
        "Kutsenits",
        "Lag",
        "MAN",
        "Mercedes-Benz",
        "Mitsubishi",
        "Neoplan",
        "Noge",
        "Opel",
        "Renault",
        "Scania",
        "Setra",
        "Smit",
        "Solaris",
        "Steyr",
        "TAM-Durabus",
        "Temsa",
        "Toyota",
        "VW",
        "Van Hool",
        "Vetter",
        "Volvo",
        "Others"
      ],


      CARAVAN: [
        "Bürstner",
        "Dethleffs",
        "Hobby",
        "Hymer/Eriba",
        "Knaus",
        "All makes",
        "ABI",
        "Adria",
        "Ahorn",
        "Airstream",
        "Alpha",
        "Arca",
        "Atlas",
        "Autoroller",
        "Autostar",
        "Avento",
        "BK Bleubird",
        "Bavaria-Camp",
        "Bawemo",
        "Beisl",
        "Bela",
        "Benimar",
        "Beyerland",
        "Bimobil",
        "Burow",
        "CI International",
        "CS Reisemobile",
        "Ca-Mo-Car",
        "Carado",
        "Caravelair",
        "Caretta",
        "Carnaby Caravans",
        "Caro",
        "Carthago",
        "Challenger",
        "Chateau",
        "Chausson",
        "Chrysler",
        "Citroen",
        "Clever",
        "Coachmen",
        "Concorde",
        "Cristall",
        "Damon",
        "Dehler",
        "Delta",
        "Dopfer",
        "Dreamer",
        "Due Erre",
        "Eifelland",
        "Elnagh",
        "Esterel",
        "Etrusco",
        "Euramobil",
        "Euro Liner",
        "Fendt",
        "Ffb/Tabbert",
        "Fiat",
        "Fleetwood",
        "Fleurette",
        "Florium",
        "Ford",
        "Ford/Reimo",
        "Forster",
        "Frankia",
        "General Motors",
        "Gigant",
        "Giottiline",
        "Globe-Traveller",
        "Globecar",
        "Glücksmobil",
        "Granduca",
        "HRZ",
        "HYMERCAR",
        "Hehn",
        "Heku",
        "Holiday Rambler",
        "Home-Car",
        "ICF",
        "Illusion",
        "Itineo",
        "Iveco",
        "Joint",
        "Kabe",
        "Karmann",
        "Kentucky",
        "Kip",
        "La Strada",
        "Lacet",
        "Laika",
        "Linne-Liner",
        "Lmc",
        "M+M Mobile",
        "MAN",
        "Ma-Bu",
        "Maesss",
        "Malibu",
        "Mazda",
        "Mclouis",
        "Mercedes-Benz",
        "Miller",
        "Mirage",
        "Mitsubishi",
        "Mobilvetta",
        "Monaco",
        "Moncayo",
        "Morelo",
        "Neo-Traveller",
        "Neotec",
        "Niesmann+Bischoff",
        "Niewiadow",
        "NobelART",
        "Nordstar",
        "Opel",
        "Orangecamp",
        "Ormocar",
        "PLA",
        "Pemberton",
        "Peugeot",
        "Phoenix",
        "Pilote",
        "Procab",
        "Pössl",
        "RMB",
        "Raclet",
        "Rapido",
        "Reimo",
        "Reisemobile Beier",
        "Renault",
        "Reydam",
        "Rimor",
        "Riva",
        "Riviera",
        "Roadcar",
        "Roadtrek",
        "Robel-Mobil",
        "Robeta",
        "Rockwood",
        "Roller Team",
        "SEA",
        "Schwabenmobil",
        "Selbstbau",
        "Sonstige/Other",
        "Sprite",
        "Stephex motorhomes",
        "Sterckeman",
        "Sun Living",
        "Sunlight",
        "Sunroller",
        "Swift",
        "T@b",
        "Tabbert",
        "Tec",
        "Tischer",
        "Trigano",
        "Triple E",
        "Ultra",
        "VANTourer",
        "VW",
        "Vario",
        "Victory",
        "Volkner",
        "Weinsberg",
        "Weippert",
        "Westfalia",
        "Wilk",
        "Willerby",
        "Wingamm",
        "Winnebago",
        "Woelcke",
        "XGO",
        "Sonstige/Other"
      ],
      
      
      
      
    
      
      CONSTRUCTION: [
        "ABG",
        "ABI",
        "Ahlmann",
        "Airmann",
        "Akermann",
        "Alasco",
        "Alufase",
        "Ammann",
        "Arden",
        "As-Motor",
        "Astra",
        "Atlas",
        "Atlas Copco",
        "Atlet",
        "Ausa",
        "BMD",
        "BST",
        "Bagela",
        "Beckmann",
        "Bell",
        "Bendini",
        "Bergmann",
        "Binimac",
        "Bison",
        "Bitelli",
        "Bobcat",
        "Bomag",
        "Brielmaier",
        "Brinkmann",
        "Brockmüller",
        "Bronto",
        "Brown-Lenox",
        "Brühl",
        "Bunker",
        "Bwb",
        "Böcker",
        "Böhringer",
        "Case",
        "Caterpillar",
        "Cela",
        "Claas",
        "Clark",
        "Cnh",
        "Coles",
        "Compair-Demag",
        "Condor",
        "Custers",
        "Cäsar",
        "Daewoo",
        "Delmag",
        "Demag",
        "Denka",
        "Dieci",
        "Dino",
        "Ditch-Witch",
        "Doosan",
        "Doppstadt",
        "Drago",
        "Dumec",
        "Dynapac",
        "Eco-Air",
        "Eder",
        "Ellinger",
        "Erkat",
        "Euclid",
        "Eurocomach",
        "Euroramm",
        "Eurotrac",
        "Extec",
        "Fai",
        "Faun",
        "Fiat-Hitachi",
        "Fiatallis",
        "Finlay",
        "Fiskars",
        "Fliegl",
        "Flottmann",
        "Foton/Eurotrac",
        "Fuchs",
        "Furukawa",
        "GSL",
        "GSR",
        "Gehlmax",
        "Genie",
        "Gipo",
        "Grabenmeister",
        "Grove",
        "Hamm",
        "Hanix",
        "Hanomag",
        "Hartl",
        "Haulotte",
        "Hausherr",
        "Hinowa",
        "Hitachi",
        "Holland Lift",
        "Husmann",
        "Huther",
        "Hydrema",
        "Hyundai",
        "Hünnebeck",
        "Ingersoll Rand",
        "Intrame",
        "Ipro",
        "Irmer+Elze",
        "Iron",
        "JCB",
        "JLG",
        "Jenz",
        "John Deere",
        "K-Trac",
        "Kaelble",
        "Kaeser",
        "Karrena",
        "Kato",
        "Keestrack",
        "Kenguru",
        "Khd Humboldt",
        "Kobelco",
        "Komatsu",
        "Kothier",
        "Kramer",
        "Krupp",
        "Kubota",
        "König",
        "Lanz",
        "Lasco",
        "Liebherr",
        "Linde",
        "Lissmac",
        "Lsb",
        "MFL",
        "MGF",
        "Mabe",
        "Manitou",
        "Masalta",
        "Masterskreen",
        "Maveco",
        "Mcmillen",
        "Menk",
        "Merlo",
        "Michigan",
        "Montabert",
        "Multione",
        "Multitel",
        "Möslein",
        "Müller",
        "NPK",
        "Nante",
        "Neuson",
        "New Holland",
        "Niftylift",
        "Nisbau",
        "Nissan",
        "Nordberg",
        "O&K",
        "Ohl",
        "Oil&Steel",
        "Olympian",
        "Omme",
        "P & H",
        "Pagliero",
        "Palazzani",
        "Parker",
        "Paus",
        "Pegson",
        "Pel-Job",
        "Peri",
        "Pkz",
        "Poclain",
        "Porsche",
        "Potain",
        "Powerscreen",
        "Ppm",
        "Pramac",
        "Putzmeister",
        "Rammax",
        "Rammer",
        "Reich",
        "Renders",
        "Ruthmann",
        "SMG",
        "STDS-Jantz",
        "Salzgitter",
        "Sambron",
        "Sany",
        "Sbm-Wageneder",
        "Schaeff",
        "Schick",
        "Schwing",
        "Sebhsa",
        "Selwood",
        "Sennebogen",
        "Simon",
        "Socage",
        "Sor",
        "Steinbock",
        "Steinweg",
        "Still",
        "Sulky",
        "Sunward",
        "Tadano",
        "Takeuchi",
        "Tamrock",
        "Tcm",
        "Tecna",
        "Teltomat",
        "Terex",
        "Tesmec",
        "Teupen",
        "Thaler",
        "Tkd",
        "Tractotechnik",
        "Tünkers",
        "Uni Hofschlepper",
        "Up-Right",
        "Van Dalfsen",
        "Verachtert",
        "Vermeer",
        "Vibromax",
        "Volvo",
        "Vögele",
        "Völker",
        "Wacker",
        "Weber",
        "Weifang",
        "Wibau",
        "Wifo",
        "Wilbert",
        "Willibald",
        "Wirtgen",
        "Wolff",
        "Wumag",
        "Yanmar",
        "Zato",
        "Zeppelin",
        "Zettelmeyer",
        "Others"
      ],
      
      
      
      //@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
      //@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
      //@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
      
      
      
      CONTAINER: [
        "A1 Container",
        "CT-Container",
        "Fliegl",
        "Fruehauf",
        "Kerex",
        "Krone",
        "Kögel",
        "Monza",
        "Morteo",
        "Schmitz Cargobull",
        "Schwarzmüller",
        "Sommer",
        "Wecon",
        "Wielton",
        "Others"
      ],
      
      
      
      //@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
      //@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
      //@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
      
      
      FORKLIFT: [
        "Agco Massey Ferguson",
        "Allis Chalmers",
        "Almocar",
        "Apache",
        "Artison",
        "Asea",
        "Atlas",
        "Atlet",
        "Ausa",
        "BKC",
        "BKS",
        "BT",
        "Baka",
        "Baker-Linde",
        "Balduin",
        "Balkancar",
        "Baoli",
        "Barrett",
        "Bartels",
        "Battioni-Pagani",
        "Baumann",
        "Belotti",
        "Bendi",
        "Bendi Truck",
        "Big Joe",
        "Bison",
        "Blue Giant",
        "Bobcat",
        "Bonser",
        "Boss",
        "Brieletta",
        "Brunilift",
        "Buda",
        "Bulmor",
        "CTC",
        "CVS Ferrari",
        "Cangaru",
        "Cardo",
        "Carer",
        "Case",
        "Caterpillar",
        "Cesab",
        "Champ",
        "Claass Unitruck",
        "Clark",
        "Clark/Drexel",
        "Cleco",
        "Climax",
        "Cmec",
        "Combilift",
        "Condor",
        "Convayancer",
        "Crown",
        "Cukurova",
        "Cvitalia",
        "Daewoo",
        "Dalian",
        "Dambach",
        "Dan Truck",
        "Datsun",
        "De Antoni",
        "Deca",
        "Dentoni",
        "Desta",
        "Detas",
        "Dieci",
        "Drexel",
        "Eagle Picher",
        "Ecoa",
        "Electricar",
        "Elwell Parker",
        "Erickson",
        "Esslingen",
        "Etwo",
        "Faba",
        "Fantuzzi",
        "Fendt",
        "Fenwick",
        "Fiat",
        "Fiora",
        "Forager",
        "Frenzen",
        "Gehl",
        "Genkinger",
        "Gerlinger",
        "Gerner",
        "Gradall",
        "Gregory",
        "Güldner",
        "Hako",
        "Halla",
        "Hamech",
        "Hanix",
        "Hanselifter",
        "Harlan",
        "Harlo",
        "Heden",
        "Heli",
        "Hendré",
        "Henley",
        "Herculift",
        "Hubtex",
        "Hunslett",
        "Hydrolift",
        "Hyster",
        "Hyundai",
        "IWS",
        "Indos",
        "Ingersoll Rand",
        "Irion",
        "Irioncar",
        "Irismann",
        "Italmacchine",
        "JCB",
        "Je-Lau",
        "Jenbacher",
        "John Deere",
        "Jumbo",
        "Jungheinrich",
        "Kaiser & Kraft",
        "Kalmar",
        "Kalmar/Irion",
        "Kd Manitou",
        "Kelvin",
        "Kempf",
        "Kesmac",
        "King Lift",
        "Komatsu",
        "Kooi-Aap",
        "Krups",
        "Kukuroma",
        "Köttgen",
        "LMV",
        "LTB",
        "Lafis",
        "Lancer-Boss",
        "Landoll",
        "Lansing",
        "Larf",
        "Laurak",
        "Lenson",
        "Letourneau",
        "Lift Dynamics",
        "Lift King",
        "Liftall",
        "Lifter",
        "Linde",
        "Ljungbymaskin",
        "Loc",
        "Logitrans",
        "Lugli",
        "Lull",
        "Luna",
        "Lungby Truck",
        "Mafi",
        "Manitou",
        "Mast",
        "Master Craft",
        "Matbro",
        "Matral",
        "Maxein",
        "Merlo",
        "Miag",
        "Mic",
        "Mijack",
        "Mikado",
        "Mitsubishi",
        "Moffett",
        "Montgomerie",
        "Montini",
        "Mora",
        "Movit",
        "Multiton",
        "NYK",
        "Namco",
        "Narrow Aisle",
        "Nissan",
        "Noble",
        "Ny+G4k",
        "O&K",
        "OMC",
        "OMG",
        "Om",
        "Om-Pimespo",
        "Ormic",
        "Ottawa",
        "Palfinger",
        "Panascopic",
        "Patria",
        "Paus",
        "Pefra",
        "Peg",
        "Pettibone",
        "Pfaff Silberblau",
        "Pgs",
        "Phb",
        "Pierrallesi",
        "Plan Truck",
        "Powerlift",
        "Prat",
        "Presto",
        "Prime Mover",
        "Princeton",
        "Puma",
        "RMF",
        "RMS",
        "Ranger",
        "Ransome",
        "Rapido",
        "Raymond",
        "Rico",
        "Rigger Lift",
        "Robur",
        "Rocla",
        "Rofan",
        "Royal",
        "SMV",
        "SSP",
        "Salev",
        "Samag",
        "Sambron",
        "Samsung",
        "Samuk",
        "Sanderson",
        "Saxby",
        "Scanlift",
        "Schaeff",
        "Schreck",
        "Sellick",
        "Semax",
        "Shaw",
        "Shinko",
        "Sichelschmidt",
        "Sideloader",
        "Sidetracker",
        "Silent Hoist/Hoist",
        "Simon",
        "Skytrak",
        "Steinbock",
        "Still",
        "Svetruck",
        "Swinger",
        "Tailift",
        "Takraft",
        "Taylor",
        "Tcm",
        "Teledyne",
        "Tennant",
        "Terex",
        "Tifon",
        "Titan",
        "Towmotor",
        "Toyota",
        "Track Mobile",
        "Translift",
        "Traverse",
        "VTA",
        "Valmet",
        "Vestergaard",
        "Volk",
        "Wagner",
        "Walsted Truck",
        "Wayne",
        "Weber",
        "White",
        "Wiedemann",
        "Wiggins",
        "Wilmat Handling",
        "Withforce",
        "Xelan",
        "Yale",
        "Yam",
        "Yang",
        "Others"
      ],
      
      
      
      //@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
      //@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
      //@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
      
      
      
      
      PUBLIC_UTILITY: [
        "Alfine",
        "Astra",
        "Augl",
        "Boschung",
        "Bremach",
        "Brock Kehrtechnik",
        "Bucher-Schörling",
        "Chevrolet",
        "Citroen",
        "DAF",
        "Duelvo",
        "Faun",
        "Fliegl",
        "Ford",
        "Hako",
        "Hansa",
        "Intrall",
        "Iveco",
        "Johnston",
        "K-Trac",
        "Kempf",
        "Küpper-Weisser",
        "Ladog",
        "MAN",
        "Magirus Deutz",
        "Mercedes-Benz",
        "Multicar",
        "Pfau",
        "Piaggio",
        "Pietsch",
        "Ravo",
        "Renault",
        "Scania",
        "Schmidt",
        "Sicas",
        "Terberg",
        "UCM",
        "Unimog",
        "VW",
        "Van Dalfsen",
        "Volvo",
        "Westa",
        "Others"
      ],
      
      
      
      //@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
      //@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
      //@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
      
      
      
      
      SEMITRAILER:  [
        "ATM",
        "Aak",
        "Ackermann Fahrzeugbau",
        "Ackermann-Fruehauf",
        "Asnæs",
        "BNG",
        "BSS",
        "Benalu",
        "Berger",
        "Blumhardt",
        "Broshuis",
        "Bulthuis",
        "Bunge",
        "Burg",
        "C.C.F.C",
        "CIMC",
        "CIMC Silvergreen",
        "Cardi",
        "Carnehl",
        "Chereau",
        "Contar",
        "DAF",
        "Dapa",
        "Doll",
        "Es-Ge",
        "F.C. Meiller",
        "FGM",
        "Faymonville",
        "Feldbinder",
        "Fliegl",
        "Floor",
        "Fluid",
        "Fruehauf",
        "GM",
        "GMF",
        "GTI",
        "General Trailer",
        "Gofa",
        "Goldhofer",
        "Groenewegen",
        "HFR",
        "HRD",
        "Hangler",
        "Hendricks",
        "Hilken",
        "Hobur",
        "Hoffmann",
        "Humbaur",
        "Hönkhaus",
        "Hüffermann",
        "Isi",
        "Istrail",
        "Itas-Cas",
        "Kaiser",
        "Kautec",
        "Kautz Sohn",
        "Kel-Berg",
        "Kempf",
        "Klaeser",
        "Knapen",
        "Kotschenreuther",
        "Kraemer",
        "Kraker",
        "Krone",
        "Kröger",
        "Kässbohrer",
        "Kögel",
        "Lag",
        "Lamberet",
        "Langendorf",
        "Leci",
        "Lecitrailer",
        "Little Dude",
        "Lohr",
        "Marques",
        "Mega",
        "Meierling",
        "Meiller",
        "Menci",
        "Menci/Santi",
        "Merceron",
        "Meusburger",
        "Molgjer",
        "Montracon",
        "Möslein",
        "Müller-Mitteltal",
        "Netam-Fruehauf",
        "Nooteboom",
        "Nopa",
        "Novatrail",
        "Närko",
        "Orten",
        "Orthaus",
        "PNO",
        "Pacton",
        "Pezzaioli",
        "Reisch",
        "Renders",
        "Ruthmann",
        "Rába",
        "Samro",
        "Sawo",
        "Scheuerle",
        "Schmitz Cargobull",
        "Schwarzmüller",
        "Sdc",
        "Setra/Kässbohrer",
        "Snedker",
        "Sommer",
        "Sor",
        "Spitzer",
        "Stas",
        "Talson",
        "TecnoKar",
        "Tirsan",
        "Trailor",
        "Tranders",
        "Trouillet",
        "Van Hool",
        "Varig",
        "Vocol",
        "Wackenhut",
        "Web Trailers",
        "Wecon",
        "Weka",
        "Wielton",
        "Zorzi",
        "Others"
      ],
      
      
      
      //@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
      //@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
      //@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
      
      
      
      
      TRACTOR:  [
        "Astra",
        "DAF",
        "Freightliner",
        "Iveco",
        "Kenworth",
        "MAN",
        "Mack",
        "Magirus Deutz",
        "Mercedes-Benz",
        "Peterbilt",
        "Renault",
        "Scania",
        "Sisu",
        "T-Ax-O",
        "Terberg",
        "Volvo",
        "Others"
      ],
      
      
      
      //@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
      //@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
      //@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
      
      
      
      
      TRAILER: [
        "Aak",
        "Ackermann Fahrzeugbau",
        "Ackermann-Fruehauf",
        "Agados",
        "Alf Fahrzeugbau",
        "Algema",
        "Annaburger",
        "Anssems  ",
        "Asnæs",
        "Atec",
        "Auwärter",
        "BNG",
        "BSS",
        "Barthau",
        "Benalu",
        "Blomenröhr",
        "Blomert",
        "Blyss",
        "Borco-Höhns",
        "Brandl",
        "Brenderup",
        "Brian James Trailers",
        "Bunge",
        "Burg",
        "Böckmann",
        "CIMC Silvergreen",
        "Carnehl",
        "Chereau",
        "Cheval Liberté",
        "Contar",
        "Dapa",
        "Daxara",
        "Demmler",
        "Dinkel",
        "Doll",
        "Eduard",
        "Eggers",
        "Es-Ge",
        "Excalibur",
        "F.C. Meiller",
        "FGM",
        "Fautras",
        "Faymonville",
        "Fb Fahrzeugbau",
        "Feldbinder",
        "Finkl",
        "Fischer",
        "Fitzel",
        "Fliegl",
        "Floor",
        "Fluid",
        "Frankenstein",
        "Franzen Efferen",
        "Fruehauf",
        "Fuchs",
        "GM",
        "GMF",
        "Gamo",
        "General Trailer",
        "Genie",
        "Gheysen & Verpoort",
        "Gilibert",
        "Gofa",
        "Goldhofer",
        "Groenewegen",
        "HFR",
        "HRD",
        "Hahn",
        "Hapert",
        "Heimann",
        "Heinemann",
        "Hendricks",
        "Henra",
        "Hilken",
        "Hobur",
        "Hoffmann",
        "Hofmann",
        "Hors",
        "Humbaur",
        "Humer",
        "Hüffermann",
        "Hürth",
        "Ifor Williams",
        "Isi",
        "Itas-Cas",
        "Jotha",
        "Jung Homburg",
        "Junghanns",
        "Kaiser",
        "Karo",
        "Kautec",
        "Kautz Sohn",
        "Kel-Berg",
        "Kempf",
        "Knies",
        "Koch",
        "Kotschenreuther",
        "Kress",
        "Krone",
        "Kröger",
        "Kumlin",
        "Kässbohrer",
        "Kögel",
        "König",
        "Lafaro",
        "Lag",
        "Lamberet",
        "Langendorf",
        "Lansing",
        "Leci",
        "Little Dude",
        "Lochmann",
        "Lohr",
        "Meiller",
        "Menci/Santi",
        "Meusburger",
        "Molgjer",
        "Montracon",
        "Multitrailer",
        "Möslein",
        "Müller-Mitteltal",
        "Netam",
        "Niewiadow",
        "Niftylift",
        "Noll",
        "Nooteboom",
        "Nopa",
        "Novatrail",
        "Närko",
        "Obermaier",
        "Orten",
        "Orthaus",
        "PNO",
        "Pacton",
        "Petersen-Rickers",
        "Pezzioli",
        "Pongratz",
        "Pvdo",
        "Reisch",
        "Renders",
        "Roka",
        "Rába",
        "Samro",
        "Saris",
        "Sawo",
        "Saxas",
        "Scheuerle",
        "Schlögl Fahrzeugbau",
        "Schmidt Fahrzeugbau",
        "Schmitz Cargobull",
        "Schwarzmüller",
        "Sdc",
        "Seico",
        "Sluis",
        "Snedker",
        "Snorkel",
        "Sommer",
        "Spier",
        "Stas",
        "Stedele",
        "Stema",
        "TEMA",
        "Tang",
        "Techau",
        "Tempus",
        "Thiel",
        "Tirsan",
        "Tpv Trailers",
        "Trailor",
        "Tranders",
        "Trouillet",
        "Unsinn Fz-Technik",
        "Van Hool",
        "Varig",
        "Vocol",
        "WEEKEND",
        "Wackenhut",
        "Web Trailers",
        "Wecon",
        "Weka",
        "Westfalia",
        "Wielton",
        "Wm Meyer",
        "Woermann",
        "Woodford Trailer",
        "Z-Trailer",
        "Zaslaw",
        "Zorzi",
        "Others"
      ] ,
      
      
      
      
      //@@@@@@@@@@@@@@@@@@
      //@@@@@@@@@@@@@@@@@
      //@@@@@@@@@@@@@@@@@@@@@
      
      TRUCK: [
        "Make",
        "Adamoli",
        "Algema",
        "Alpha",
        "Astra",
        "Atlas",
        "Avia",
        "DAF",
        "DFSK Minitrucks",
        "Daewoo Motor Polska",
        "Daihatsu",
        "Demag",
        "Demak",
        "Epsilon",
        "Fassi",
        "Faun",
        "Fitzel",
        "Fleetwood",
        "Ford",
        "Freightliner",
        "Fuchs",
        "Ginaf",
        "Gottwald",
        "Grove",
        "Heitling",
        "Hiab",
        "Hmf",
        "Hors",
        "Hyundai",
        "Isuzu",
        "Iveco",
        "Jonsered",
        "Karrena",
        "Kenworth",
        "Kress",
        "Krupp",
        "Liaz",
        "Liebherr",
        "MAN",
        "Mack",
        "Magirus Deutz",
        "Meiller",
        "Mercedes-Benz",
        "Mitsubishi",
        "Multitel",
        "Nissan",
        "Palfinger",
        "Pegaso",
        "Peterbilt",
        "Ppm",
        "Putzmeister",
        "Reisch",
        "Renault",
        "Saxas",
        "Scania",
        "Sisu",
        "Steyr",
        "Tatra",
        "Terberg",
        "Unimog",
        "Ural",
        "VW",
        "Volvo",
        "Wielton",
        "Others"
      ] ,
      
      
      
      
      //@@@@@@@@@@@@@@@@@@
      //@@@@@@@@@@@@@@@@@
      //@@@@@@@@@@@@@@@@@@@@@
      
      VAN: [
        "Make",
        "Ausa",
        "Borco-Höhns",
        "Chevrolet",
        "Chrysler",
        "Citroen",
        "DAF",
        "Dacia",
        "Daewoo Motor Polska",
        "Daihatsu",
        "Dodge",
        "Effedi",
        "Fiat",
        "Ford",
        "GAZ",
        "General Motors",
        "Giotti Victoria",
        "Gmc",
        "Hors",
        "Hyundai",
        "Intrall",
        "Isuzu",
        "Iveco",
        "Kia",
        "Kress",
        "Kuvvetli",
        "MAN",
        "Mazda",
        "Mercedes-Benz",
        "Mitsubishi",
        "Multicar",
        "Nissan",
        "Opel",
        "Peugeot",
        "Piaggio",
        "Renault",
        "Seat",
        "Skoda",
        "Subaru",
        "Suzuki",
        "Toyota",
        "Unimog",
        "VW",
        "Volvo",
        "Others"
      ]  
  }




