export const CarsProperties= {
    //air conditionind
    'No Climatisation' : 'NO_CLIMATISATION',
    'Automatic Air Condition' : 'AUTOMATIC_AIR_CONDITIONING',
    'Manual or Automatic Climatisation' : 'MANUAL_OR_AUTOMATIC_CLIMATISATION',
    'Automatic Climatisation, 2 Zones' : 'AUTOMATIC_CLIMATISATION_2_ZONES',
    'Automatic Climatisation, 3 Zones' : 'AUTOMATIC_CLIMATISATION_3_ZONES',
    'Automatic Climatisation, 4 Zones' : 'AUTOMATIC_CLIMATISATION_4_ZONES',
    //history
    'Full service history' : 'FULL_SERVICE',
    'Waranty' : 'WARANTY',
    'Non-smoker vehicle' : 'NON_SMOKER',
    'Roadworthy' : 'ROADWORTHY',
    'Vehicle is damaged' : 'VEHICLE_IS_DAMAGED',
    //Lifestyle
     'Adventure Cars' : 'ADVENTURE',
    'Classic Cars' : 'CLASSIC',
    'Vintage Cars' : 'VINTAGE',
    'Family Cars' : 'FAMILY',
    'Luxuury Cars' : 'LUXARY',
    'Other Cars' : 'OTHER',
    'Muscle Cars' : 'MUSCLE',
    'Old Cars' : 'OLD',
    'Tradie Cars' : 'TRADIE',
    'Urban Cars' : 'URBAN',
    //bodyType
    'Sedan' : 'SEDAN',
    'Hatchback' : 'HATCHBACK',
    'Convertible' : 'CONVERTIBLE',
    'Commercial' : 'COMMERCIAL',
    'Utility' : 'UTILITY',
    'Suv' : 'SUV',
    'Coupe' : 'COUPE',
    'Van' : 'VAN',
    'Wagon' : 'WAGON',
    'Classic' : 'CLASSIC',
    'Toucher' : 'TOURER',
    'Naked Bike' :  'NAKED_BIKE',
    'Enduro Bike' : 'ENDURO_BIKE',
    'Supersport' : 'SUPERSPORT',
    'Scooter' : 'SCOOTER',
    'Chopper / Cruiser' : 'CHOPPER',
    'Quad' : 'QUAD'
}
